### ISSUE TITLE
Compatibility with Stripe Add-On

### ISSUE THREAD

**Issue by redpupmedia** [tyxla/Gravity-Forms-Multiple-Form-Instances#18]
Hello.

WP - 4.4.2
GF - 1.9.17.5 
GF Stripe Add On - 2.0
GF-MFI - 1.1

Error received on form submission: `Unable to authorize card. No response from Stripe.js.`

Disabling the GF-MFI plugin resolved the issue.

**Comment by tyxla** [comment]
Hey @redpupmedia 

Thanks for reporting! I'll have a look as soon as possible.

**Comment by tyxla** [comment]
Hey @redpupmedia ,

Unfortunately, these two plugins are not compatible, as they contradict each other. In order for multiple instances of the same form to work, the IDs must be replaced. And if the IDs are replaced, the Stripe addon does not work, as it makes a request on behalf of an unexisting form ID. Since the Stripe addon does not offer any custom events that we can hook on, there is nothing that can be done to make these two plugins compatible.

I believe that in your case GF-MFI wont work - it is best if you don't use it for that case, and use different `tabindex` for each form instance.

Good luck!

**Comment by redpupmedia** [comment]
Thanks @tyxla 
I had come to the same conclusion. Thankfully, my need for GF-MFI has passed for now.

But very useful plugin. Thank you.

**Comment by tyxla** [comment]
Thank you. Good luck with your project.

**Comment by Coop9200** [comment]
Thank you, I had this same error.
